export const ADD_BRAND_REQUEST = "ADD_BRAND_REQUEST";
export const EDIT_BRAND_REQUEST = "EDIT_BRAND_REQUEST";
export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST";
export const FETCH_LIST_BRAND_REQUEST = "FETCH_LIST_BRAND_REQUEST";
export const FETCH_LIST_BRAND_SUCCESS = "FETCH_LIST_BRAND_SUCCESS";
export const FETCH_LIST_BRAND_FAILURE = "FETCH_LIST_BRAND_FAILURE";
export const FETCH_BRAND_DETAIL_REQUEST = "FETCH_BRAND_DETAIL_REQUEST";
export const FETCH_BRAND_DETAIL_REQUEST_SUCCESS =
  "FETCH_BRAND_DETAIL_REQUEST_SUCCESS";
export const FETCH_BRAND_DETAIL_REQUEST_FAILURE =
  "FETCH_BRAND_DETAIL_REQUEST_FAILURE";
