export const FETCH_LIST_GUEST_REQUEST = "FETCH_LIST_GUEST_REQUEST";
export const FETCH_LIST_GUEST_SUCCESS = "FETCH_LIST_GUEST_SUCCESS";
export const FETCH_LIST_GUEST_ERROR = "FETCH_LIST_GUEST_ERROR";


export const FETCH_GUEST_INFOR_REQUEST ="FETCH_GUEST_INFOR_REQUEST";
export const FETCH_GUEST_INFOR_SUCCESS ="FETCH_GUEST_INFOR_SUCCESS";
export const FETCH_GUEST_INFOR_ERROR ="FETCH_GUEST_INFOR_ERROR";

export const EDIT_GUEST_REQUEST ="EDIT_GUEST_REQUEST";
export const EDIT_GUEST_SUCCESS ="EDIT_GUEST_SUCCESS";
export const EDIT_GUEST_ERROR ="EDIT_GUEST_ERROR";

export const CHANGE_STATUS_REQUEST ="CHANGE_STATUS_REQUEST"

export const UP_TO_ADMIN_REQUEST ="UP_TO_ADMIN_REQUEST"

export const DELETE_USER_REQUEST ="DELETE_USER_REQUEST"

export const SEARCH_USER_REQUEST ="SEARCH_USER_REQUEST"
export const SEARCH_USER_SUCCESS ="SEARCH_USER_SUCCESS"
export const SEARCH_USER_ERROR ="SEARCH_USER_ERROR"