export const FETCH_LIST_GUEST_REQUEST = "FETCH_LIST_GUEST_REQUEST";
export const FETCH_LIST_GUEST_SUCCESS = "FETCH_LIST_GUEST_SUCCESS";
export const FETCH_LIST_GUEST_ERROR = "FETCH_LIST_GUEST_ERROR";
