export const FETCH_LIST_GUEST_REQUEST = "FETCH_LIST_GUEST_REQUEST";
export const FETCH_LIST_GUEST_SUCCESS = "FETCH_LIST_GUEST_SUCCESS";
export const FETCH_LIST_GUEST_ERROR = "FETCH_LIST_GUEST_ERROR";


export const FETCH_GUEST_INFOR_REQUEST ="FETCH_GUEST_INFOR_REQUEST";
export const FETCH_GUEST_INFOR_SUCCESS ="FETCH_GUEST_INFOR_SUCCESS";
export const FETCH_GUEST_INFOR_ERROR ="FETCH_GUEST_INFOR_ERROR";
