export const FETCH_LIST_HOTEL_REQUEST = "FETCH_LIST_HOTEL_REQUEST";
export const FETCH_LIST_HOTEL_SUCCESS = "FETCH_LIST_HOTEL_SUCCESS";
export const FETCH_LIST_HOTEL_FAILURE = "FETCH_LIST_HOTEL_FAILURE";
export const ADD_HOTEL_REQUEST = "ADD_HOTEL_REQUEST";
export const EDIT_HOTEL_REQUEST = "EDIT_HOTEL_REQUEST";
export const DELETE_HOTEL_REQUEST = "DELETE_HOTEL_REQUEST";

export const FETCH_PAGINATION_HOTEL_REQUEST = "FETCH_PAGINATION_HOTEL_REQUEST";

export const FETCH_HOTEL_DETAIL_REQUEST = "FETCH_HOTEL_DETAIL_REQUEST";
export const FETCH_HOTEL_DETAIL_REQUEST_SUCCESS =
  "FETCH_HOTEL_DETAIL_REQUEST_SUCCESS";
export const FETCH_HOTEL_DETAIL_REQUEST_FAILURE =
  "FETCH_HOTEL_DETAIL_REQUEST_FAILURE";
