export const FETCH_LIST_HOTEL_REQUEST = "FETCH_LIST_HOTEL_REQUEST";
export const FETCH_LIST_HOTEL_SUCCESS = "FETCH_LIST_HOTEL_SUCCESS";
export const FETCH_LIST_HOTEL_FAILURE = "FETCH_LIST_HOTEL_FAILURE";
