export const FETCH_LIST_ROOMTYPE_REQUEST1 ="FETCH_LIST_ROOMTYPE_REQUEST1";
export const FETCH_LIST_ROOMTYPE_SUCCESS1 ="FETCH_LIST_ROOMTYPE_SUCCESS1";

export const ADD_PROMO_REQUEST = "ADD_PROMO_REQUEST";
export const ADD_PROMO_SUCCESS = "ADD_PROMO_SUCCESS";

export const FETCH_LIST_PROMOS_REQUEST ="FETCH_LIST_PROMOS_REQUEST";
export const FETCH_LIST_PROMOS_SUCCESS="FETCH_LIST_PROMOS_SUCCESS";
export const FETCH_LENGTH_PROMO_SUCCESS ="FETCH_LENGTH_PROMO_SUCCESS"

export const DELETE_PROMO_REQUEST ="DELETE_PROMO_REQUEST";
export const DELETE_PROMO_SUCCESS ="DELETE_PROMO_SUCCESS";

export const FETCH_LIST_ACTIVE_PROMO_REQUEST ="FETCH_LIST_ACTIVE_PROMO";
export const FETCH_LIST_ACTIVE_PROMO_SUCCESS ="FETCH_LIST_ACTIVE_PROMO_SUCCESS";

export const EDIT_PROMO_REQUEST ="EDIT_PROMO_REQUEST ";