export const FETCH_LIST_ROOMTYPE_REQUEST = "FETCH_LIST_ROOMTYPE_REQUEST";
export const FETCH_LIST_ROOMTYPE_SUCCESS = "FETCH_LIST_ROOMTYPE_SUCCESS";
export const FETCH_LIST_ROOMTYPE_ERROR = "FETCH_LIST_ROOMTYPE_ERROR";


export const FETCH_ROOMTYPE_DETAIL_REQUEST="FETCH_ROOMTYPE_DETAIL_REQUEST";
export const FETCH_ROOMTYPE_DETAIL_SUCCESS="FETCH_ROOMTYPE_DETAIL_SUCCESS";
export const FETCH_ROOMTYPE_DETAIL_ERROR="FETCH_ROOMTYPE_DETAIL_ERROR";