export const FETCH_LIST_ROOMTYPE_REQUEST = "FETCH_LIST_ROOMTYPE_REQUEST";
export const FETCH_LIST_ROOMTYPE_SUCCESS = "FETCH_LIST_ROOMTYPE_SUCCESS";
export const FETCH_LIST_ROOMTYPE_ERROR = "FETCH_LIST_ROOMTYPE_ERROR";

export const FETCH_ROOMTYPE_DETAIL_REQUEST = "FETCH_ROOMTYPE_DETAIL_REQUEST";
export const FETCH_ROOMTYPE_DETAIL_SUCCESS = "FETCH_ROOMTYPE_DETAIL_SUCCESS";
export const FETCH_ROOMTYPE_DETAIL_ERROR = "FETCH_ROOMTYPE_DETAIL_ERROR";

export const ADD_ROOMTYPE_REQUEST = "ADD_ROOMTYPE_REQUEST";
export const DELETE_ROOMTYPE_REQUEST = "DELETE_ROOMTYPE_REQUEST";
export const EDIT_ROOMTYPE_REQUEST = "EDIT_ROOMTYPE_REQUEST";

export const SEARCH_ROOMTYPE_REQUEST = "SEARCH_ROOMTYPE_REQUEST";

//////////////////////////////////////////////////

export const FETCH_LIST_HOTEL_OPTION_REQUEST =
  "FETCH_LIST_HOTEL_OPTION_REQUEST";
export const FETCH_LIST_HOTEL_OPTION_SUCCESS =
  "FETCH_LIST_HOTEL_OPTION_SUCCESS";
export const SELECT_BRAND_OF_HOTEL = "SELECT_BRAND_OF_HOTEL";
export const ADD_ROOM_REQUEST = "ADD_ROOM_REQUEST";
export const ADD_ROOM_SUCCESS = "ADD_ROOM_SUCCESS";

export const GET_ALL_ROOM_BY_BRANDID_REQUEST =
  "GET_ALL_ROOM_BY_BRANDID_REQUEST";
export const GET_ALL_ROOM_BY_BRANDID_SUCCESS =
  "GET_ALL_ROOM_BY_BRANDID_SUCCESS";

export const RESET_ROOMS_STATE_ON_REDUX = "RESET_ROOMS_STATE_ON_REDUX";

export const DELETE_ROOM_REQUEST = "DELETE_ROOM_REQUEST";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";

export const PUSH_ROOM_ITEM_DATA_TO_STORE ="PUSH_ROOM_ITEM_DATA_TO_STORE";

export const EDIT_ROOM_REQUEST ="EDIT_ROOM_REQUEST";

