export const FETCH_LIST_ROOMTYPE_REQUEST = "FETCH_LIST_ROOMTYPE_REQUEST";
export const FETCH_LIST_ROOMTYPE_SUCCESS = "FETCH_LIST_ROOMTYPE_SUCCESS";
export const FETCH_LIST_ROOMTYPE_ERROR = "FETCH_LIST_ROOMTYPE_ERROR";


export const FETCH_ROOMTYPE_DETAIL_REQUEST="FETCH_ROOMTYPE_DETAIL_REQUEST";
export const FETCH_ROOMTYPE_DETAIL_SUCCESS="FETCH_ROOMTYPE_DETAIL_SUCCESS";
export const FETCH_ROOMTYPE_DETAIL_ERROR="FETCH_ROOMTYPE_DETAIL_ERROR";

export const ADD_ROOMTYPE_REQUEST ="ADD_ROOMTYPE_REQUEST";
export const DELETE_ROOMTYPE_REQUEST ="DELETE_ROOMTYPE_REQUEST";
export const EDIT_ROOMTYPE_REQUEST ="EDIT_ROOMTYPE_REQUEST";

export const SEARCH_ROOMTYPE_REQUEST ="SEARCH_ROOMTYPE_REQUEST";