export const GET_ALL_ROOM_RESERVATION_REQUEST =
  "GET_ALL_ROOM_RESERVATION_REQUEST";
export const GET_ALL_ROOM_RESERVATION_SUCCESS =
  "GET_ALL_ROOM_RESERVATION_SUCCESS";

export const RESET_LIST_ROOM_RESERVATION_ON_REDUX =
  "RESET_LIST_ROOM_RESERVATION_ON_REDUX";

////// get only reservation

export const GET_ALL_RESERVATION_REQUEST = "GET_ALL_RESERVATION_REQUEST";
export const GET_ALL_RESERVATION_SUCCESS = "GET_ALL_RESERVATION_SUCCESS";

export const FILTER_FOLLOW_PENDDING_STATUS = "FILTER_FOLLOW_PENDDING_STATUS";
export const FILTER_FOLLOW_COMPLETED_STATUS = "FILTER_FOLLOW_COMPLETED_STATUS";
export const FILTER_FOLLOW_CANCELLED_STATUS = "FILTER_FOLLOW_CANCELLED_STATUS";

export const CHANGE_STATUS_COMPLETED_REQUEST =
  "CHANGE_STATUS_COMPLETED_REQUEST";

export const CHANGE_STATUS_CANCELLED_REQUEST =
  "CHANGE_STATUS_CANCELLED_REQUEST";
/////////////////////////////////////////
export const CHANGE_STATUS_PAYMENT_REQUEST = "CHANGE_STATUS_PAYMENT_REQUEST";
export const CHANGE_STATUS_PAYMENT_SUCCESS = "CHANGE_STATUS_PAYMENT_SUCCESS";
